drop schema if exists templates CASCADE;
create schema templates;

create table templates._base (
    id              bigint generated by default as IDENTITY,
    created_at      TIMESTAMP WITH time zone,
    updated_at     TIMESTAMP WITH time zone,
    created_by      varchar(512),
    updated_by     varchar(512),
    schema_version  varchar(512) default 'alpha',

    primary key (id)
);

comment on table templates._base is 'Commond fields for all tables';
comment on column templates._base.id is 'Default primary key';
comment on column templates._base.created_at is 'When this row was created.';
comment on column templates._base.updated_at is 'When was this row modified.';
comment on column templates._base.created_by is 'Who/what created this row.';
comment on column templates._base.updated_by is 'Who/what modified this row.';
comment on column templates._base.schema_version is 'The schema version that created this table.';

create table templates._logbase (
    logtime         timestamp with time zone default now(),
    logger          varchar(255) default 'system',
    logmessage      text,
    srcfile         varchar(516),
    srcobject       varchar(516),
    srcline         int,
    loglevel        varchar(255),
    srcip           inet,
    srcbrowser      varchar(255),
	logchain 	    bigint,
	logmarker	    varchar(255),

    like templates._base including all
);

comment on table templates._logbase is 'Basetable for a templates._logbase.';
comment on column templates._logbase.logtime is 'Event time';
comment on column templates._logbase.logger is 'Source of the event';
comment on column templates._logbase.logmessage is 'Event message';
comment on column templates._logbase.srcfile is 'Source file which generated this message';
comment on column templates._logbase.srcobject is 'Which object generated this message';
comment on column templates._logbase.srcline is 'Which source line generated this message';
comment on column templates._logbase.loglevel is 'Event class: DEBUG/AUDIT/ERROR/NOTICE...';
comment on column templates._logbase.srcip is 'Which ip address generated this event';
comment on column templates._logbase.srcbrowser is 'Model of browser generating this event';
comment on column templates._logbase.logchain is 'templates._logbase seqeunce identifier';
comment on column templates._logbase.logmarker is 'Marker for this templates._logbase chain';
